---
title: "R-01. Basic Notebook"
output: html_notebook
---


```{r}
getwd()
```


```{r}
print(pi)
print(pi, digits = 3)
```

```{r}
cat(1,':','a','\n',2,':','b','\n') # insert spaces, automatically
cat(1,':','a','\n',2,':','b','\n',sep='')
```

```{r}
# variable, data type
var1 <- 'aaa'
var2 <- 111
var3 <- Sys.Date()
var4 <- c('a','b','c')

print(var1)
print(var2)
print(var3)
print(var4)
```

```{r}
# all variables
objects()
```

```{r}
ls()
```

```{r}
objects(all.names=TRUE)
```

```{r}
# delete a variable
rm(var1)
ls()
```

```{r}
# delete all variables
rm(list=ls())
ls()
```

```{r}
print(3 / 10)
print(3 %% 10)
print(3 %/% 10)
```

```{r}
# string to numeric type
as.numeric("2") + as.numeric("5")
```

```{r}
print(T&F)
print(T|F)
print(!T)
```

```{r}
# NA : Not Available
sum(1,2,3,NA,na.rm=T)
sum(1,2,3,NA)
```

```{r}
sum(NULL, 1, 2)
cat(NULL, 1, 2, '\n')
```

```{r}
# type : factor
gender <- factor('m', c('m','f'))
print(nlevels(gender))
print(levels(gender))
print(gender)
```

```{r}
gender2 <- factor('c', c('m','f'))
print(gender2)
```

```{r}
Sys.Date()
Sys.time()
date()
```

```{r}
as.Date('2021년 1월 20일', format='%Y년 %m월 %d일')
```

```{r}
as.Date('2021-01-20') - as.Date('2021-01-10')
```

```{r}
x = 10
if (x > 0) {
  print('positive')
} else if (x==0) {
  print('zero')
} else {
  print('negative')
}
```

```{r}
x = 0
while(TRUE) {
  x <- x+1
  if (x==6) break
  if (x %% 2 == 0) next # continue
  print(x)
}
```

```{r}
x <- 10
for (i in 1:x) {
  print(i)
}
```

```{r}
n <- 10
ifelse(n %% 2 == 0, 'even', 'odd')
```

```{r}
score <- c(85, 29, 49, 90, 100, 68)
min(score)
max(score)
mean(score)
summary(score)
```

```{r}
myfunction <- function(a, b=10) {
  return (a * b)
}

myfunction(4, 5)
myfunction(80)
```

```{r}
install.packages("ggplot2")
install.packages("dplyr")
```

```{r}
installed.packages()
.libPaths()
```

```{r}
# loading a package
library(ggplot2)
```

```{r}
# vector
vec1 <- c(1,2,3,4,'5')
cat("vector :", vec1, '\n')
vec1[3]
vec1[-1]
vec1[2:4]

vec1 <- c(vec1, 7)
cat("new vector :", vec1, '\n')
vec1[9] = 9
print(vec1)

vec1 <- append(vec1, c(10, 11), after=3)
cat("append :", vec1,'\n')

var3 <- c(10,20,30)
print(union(vec1, var3))

fruits <- c(10,20,30)
names(fruits) <- c("apple","banana","orange")
print(fruits)
print(fruits[1])

seq(1,10)
seq(1,10,3)

NROW(fruits)

vec7 <- c(1, 2, 3, 4, 5, 6, 7)
100 %in% vec7
```

```{r}
# matrix
mat1 <- matrix(c(1,2,3,4)); mat1
mat3 <- matrix(c(1,2,3,4), nrow = 2); mat3
mat3[,1]
mat3[1,]
mat3[1,1]
mat3[-1,]

mat4 <- matrix(c(1,2,3,4,5,6,7,8,9), nrow = 3, byrow = T); mat4
mat4 <- rbind(mat4, c(11, 12, 13)); mat4
mat4 <- matrix(c(1,2,3,4,5,6,7,8,9), nrow = 3, byrow = F); mat4
mat4 <- rbind(mat4, c(15, 16, 17, 18)); mat4 # 남는 부분 버림
mat4 <- rbind(mat4, c(19, 20)); mat4 # 기존 데이터 재사용

mat5 <- matrix(c('a', 'b', 'c', 'd'), nrow = 2, byrow = T); mat5
mat5 <- cbind(mat5, c('e', 'f')); mat5
colnames(mat5) <- c("First", "Second", "Third")
rownames(mat5) <- c("row1", "row2")
mat5

x <- matrix(1:9, nrow=3)
x * 2
x / 2
x + 2
x - 2
x + x
x - x

x %*% x # 행렬간 곱셈

x <- matrix(1:4, ncol = 2)
solve(x) # 역행렬
x %*% solve(x) # identity matrix

t(x) # 전치 행렬
nrow(x)
ncol(x)
```

```{r}
# array
array1 <- array(c(1:12), dim = c(4, 3)); array1
array2 <- array(c(1:12), dim = c(2, 2, 3)); array2
array2[1,1,3]
array2[,1,3]
array2[1,,]
array2[,2,]
```

```{r}
# list
list1 <- list(name = 'John Doe', address = 'Seoul, Korea', phone =
'010-0000-0000', salary = 1000); list1

list1$name # 리스트이름$키
list1[1]
list1[1:2]
list1[3]
list1[c(1, 3)]

# 리스트 요소 추가
list1$birth <- '1980-5-7'
list1$name <- c("John Doe", "Johnny"); list1

# 리스트 요소 삭제
list1$birth <- NULL; list1
```

```{r}
# dataframe
no <- c(1, 2, 3, 4)
name <- c("Apple", "Peach", "Banana", "Grape")
price <- c(500, 200, 100, 50)
qty <- c(5, 2, 4, 7)
# 벡터로 부터 생성 
sales <- data.frame(NO = no, NAME = name, PRICE = price, QTY = qty); sales

# 행렬로 부터 생성
sales2 <- matrix(c(1, 'Apple', 500, 5,
                  2, 'Peach', 200, 2,
                  3, 'Banana', 100, 4,
                  4, 'Grape', 50, 7), nrow = 4, byrow = T); sales2

df1 <- data.frame(sales2); df1

# 데이터프레임이름$컬럼이름, 인덱스
sales$NAME
sales[1, 3]
sales[1,]
sales[,1]

subset(sales, qty < 5)

df1 <- data.frame(name = c('apple', 'banana', 'cherry'),
                  price = c(300, 200, 100)); df1
df2 <- data.frame(name = c('apple', 'cherry', 'berry'),
                  qty = c(10, 20, 30)); df2

merge(df1, df2)
merge(df1, df2, all = T) # outer join

# 특정 컬럼 추출
no <- c(1, 2, 3, 4)
name <- c("장동건", "김윤석", "송강호", "최민식")
address <- c("서울", "대전", "포항", "경주")
phone <- c(1111, 2222, 3333, 4444)
hobby <- c("독서", "미술", "낚시", "등산")
member <- data.frame(NO = no, NAME = name, ADDRESS = address,
                    PHONE = phone, HOBBY = hobby)
member

member2 <- subset(member, select = c(NO, NAME, PHONE)); member2
member3 <- subset(member, select = -PHONE); member3
colnames(member3) <- c("번호", "이름", "주소", "취미"); member3
```

