---
title: "R-02. Load External Data"
output: html_notebook
---

```{r}
list.files()
list.files('../data-files/')
list.files(recursive = T) # 하위 디렉터리 파일 표시
list.files(all.files = T) # 숨김 파일 표시
```

```{r}
# 텍스트 파일 읽기
scan1 <- scan('../data-files/scan-1.txt'); scan1
scan2 <- scan("../data-files/scan-2.txt", what = ""); scan2 # 문자열로 읽어옴

data <- scan(); data # 입력 없이 엔터를 치면 종료
input2 <- scan(what = ""); input2 # 문자 입력 받을 때 what = ""
input3 <- readline(); input3 # 한 줄 읽기
input4 <- readline("Input your name : "); input4
input5 <- readLines("../data-files/scan-4.txt"); input5 # 파일을 한 줄씩 읽어서 벡터에 담음

# 텍스트 파일 -> 데이터 프레임
fruits <- read.table("../data-files/fruits.txt"); fruits
fruits <- read.table("../data-files/fruits.txt", header = T); fruits # 헤더를 첫 번째 행으로 인식

fruit2 <- read.table("../data-files/fruits-2.txt"); fruit2
fruit2 <- read.table("../data-files/fruits-2.txt", skip = 2); fruit2 # 두개를 건너 뛴다
fruit2 <- read.table("../data-files/fruits-2.txt", nrows = 2); fruit2

fruits3 <- read.table("../data-files/fruits.txt",header = T,nrows = 2); fruits3
```

```{r}
# csv 파일 읽기
fruit3 <- read.csv("../data-files/fruits-3.csv"); fruit3
fruit4 <- read.csv("../data-files/fruits-4.csv"); fruit4

fruit4 <- read.csv("../data-files/fruits-4.csv", header = F); fruit4;
label <- c("NO", "NAME", "PRICE", "QTY")
fruit4 <- read.csv("../data-files/fruits-4.csv", header = F, col.names = label); fruit4
```

```{r}
install.packages("sqldf")
install.packages("googleVis")

library(sqldf)
library(googleVis)
```


```{r}
Fruits # googlevis 패키지의 Fruits 데이터
write.csv(Fruits, "../data-files/fruits-sql.csv", quote = F)
```


```{r}
# SQL로 파일 읽기
fruits2 <- read.csv.sql("../data-files/fruits-sql.csv", sql = "SELECT * FROM file WHERE Year = 2008"); fruits2
```


```{r}
install.packages("readxl")
library(readxl)
```


```{r}
# Excel 파일 데이터 읽기
df_exam <- read_excel("../data-files/excel_exam.xlsx")
df_exam <- as.data.frame(df_exam); df_exam
```

```{r}
# Rdata 파일에 데이터 쓰기/읽기
# Rdata 파일 : R 전용 데이터 파일 (R에서 읽고 쓰는 속도가 빠르고 용량 적음)

# 데이터 저장
save(df_exam, file = "../data-files/df_exam.rda")
rm(df_exam); #df_exam
load("../data-files/df_exam.rda"); df_exam
```

```{r}
# 클립보드 내용 -> 데이터 프레임으로
# 내용을 ctrl+c 로 복사 후
fruits6 <- read.delim(pipe("pbpaste"), header = T); fruits6
```


```{r}
install.packages("RJDBC")
library(RJDBC)
```


```{r}
# 데이터베이스 연동
driver2 <- JDBC("com.mysql.cj.jdbc.Driver", "mysql-connector-java-8.0.23.jar", identifier.quote = "'")
conn2 <- dbConnect(driver2,
"jdbc:mysql://127.0.0.1:3306/libweb?serverTimezone=UTC",
"ssacuser", "ssac123!@#")
rs2 <- dbGetQuery(conn2, "select * from library limit 1, 10"); rs2
dbDisconnect(conn2)
```
